version: "3.8"

services:
  data-bbe:
    build: ./db
    restart: unless-stopped
    volumes:
      - bbe-app-data:/var/lib/couchdb/data
      - ./keygen/keypair/ini:/opt/couchdb/etc/local.d
    environment:
      COUCHDB_USER: couchdbuser
      POSTGRES_PASSWORD: couchdbpassword
    network: internal_network
  auth-bbe:
    build: ./user-manager
    restart: unless-stopped
    volumes:
      - ./keygen/keypair:/etc/user-manager/keypair
    depends_on:
      - data-bbe
    network: internal_network
    ports:
      - "4000:4000"

volumes:
  bbe-app-data: {}
